spring.application.name=centralization
# URL de conexión de la base de datos MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/centralizacion?serverTimezone=UTC

# Credenciales de acceso de tu servidor MySQL
spring.datasource.username=root
spring.datasource.password=Yorga#131706

# Driver de conexión de base de datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=U29mdGdpY0NlbnRyYWxpemFjaW9uU2VjcmV0S2V5MjAyNDEy
jwt.expiration=86400000
